Fixing
Ovenn-lab/coingate-node pull request #1
Opened 2022-10-06 13:45 UTC by Doomann

2022-10-06 14:10 UTC, arnasledev requested changes

2022-10-06 14:10 UTC, arnasledev commented on src/Modules/Client/CoinGate.client.ts
> +      // if (requestType === RequestTypeEnum.POST) {
tai sito dar reik? jei ne tai naikink ji

2022-10-07 10:14 UTC, arnasledev requested changes

2022-10-07 10:14 UTC, arnasledev commented on src/Exception/ErrorHandler.ts
> +      case HttpStatusEnum.INTERNAL_SERVER_ERROR |
ne taip apsiraso dvigubi case'ai, apsiraso:

```ts
case HttpStatusEnum.INTERNAL_SERVER_ERROR:
case HttpStatusEnum.GATEWAY_TIMEOUT:
```

ir taip nusirodo, kad du case'ai

2022-10-07 10:15 UTC, arnasledev requested changes

2022-10-07 10:15 UTC, arnasledev commented on test/PublicService.spec.ts
> -    test('should call getCurrencies method with params for merchant pay currencies and selected currency kind', () => {
del ko isemei sita?

2022-10-07 10:16 UTC, arnasledev reviewed
jeigu isemei ta komentara:

```ts
// if (requestType === RequestTypeEnum.POST) {
    //   headers = {
    //     'Content-Type': 'application/x-www-form-urlencoded'
    //   };
    // }
```

tai prasuk build'a per nauja, kad ir is ten isimtu

2022-10-07 10:24 UTC, Doomann commented on test/PublicService.spec.ts
> -    test('should call getCurrencies method with params for merchant pay currencies and selected currency kind', () => {
nes nebereik paduot jokio param cia
![image](https://user-images.githubusercontent.com/80388518/194532576-1ac480d9-a71d-48b7-8206-47a5898ec3ed.png)

2022-10-07 10:52 UTC, arnasledev approved these changes

2022-10-07 10:52 UTC, merged